CREATE TABLE ITEM (
    ID NUMBER NOT NULL,
    CONSTRAINT ITEM_ID PRIMARY KEY(ID),
    DESCRIPTION NVARCHAR(30) NOT NULL
);

CREATE SEQUENCE ITEM_SEQ MINVALUE 1 MAXVALUE 1000000000 START WITH 1 INCREMENT BY 1;